variables:
  MAVEN_CLI: "-Ddocker.registry=$DOCKER_REGISTRY -Dhelm.deploy.url=$HELM_REGISTRY -Dhelm.deploy.type=$HELM_TYPE -Dmaven.deploy.releases=$MAVEN_DEPLOY_RELEASES -Dmaven.deploy.snapshots=$MAVEN_DEPLOY_SNAPSHOTS --batch-mode --errors --fail-fast --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

default:
  image: maven:3.8.4-jdk-17

stages:
  - deploy

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH =~ "/maven/release/" && $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_COMMIT_TAG != "" && $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_COMMIT_BRANCH !~ "/maven/release/" || $CI_COMMIT_TAG == ""
  artifacts:
    paths:
      - target/php/composer.json
      - target/php/composer.lock
    when: always
  before_script:
    - curl -sSL https://packages.sury.org/php/README.txt | bash -x
    - apt-get update -y
    - apt-get install -y php8.1 php8.1-curl php8.1-dom php8.1-gd php8.1-mbstring php8.1-xml php8.1-zip
  script:
    - mvn $MAVEN_CLI -s .mvn/settings.xml deploy
